CREATE TABLE IF NOT EXISTS TB_CLIENTE (
    ID BIGSERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    EMAIL VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TB_PRODUTO (
    ID BIGSERIAL PRIMARY KEY,
    CODIGO VARCHAR(10) NOT NULL UNIQUE,
    NOME VARCHAR(100) NOT NULL,
    PRECO NUMERIC(10, 2) NOT NULL,
    MARCA VARCHAR(50)
);
